# cryfic configuration file

# The system wide configuration file is located in /etc

# Verify full signature and not only hash, requires the signed config to disable
sign=0
# Report errors
verbose=99
# Report errors to stderr if verbose is turned on
stderr=1
# Report errors to syslog
syslog=0
